from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session, joinedload
from sqlalchemy import desc
from typing import List, Optional
import uuid

from ...db.database import get_db
from ...models.species import Species
from ...models.category import Category
from ...models.observation import Observation
from ...schemas.species import SpeciesResponse, SpeciesDetailResponse, SpeciesCreate
from ...schemas.category import CategoryResponse

router = APIRouter(
    prefix="",
    tags=["species", "categories"]
)

@router.post("/species", response_model=SpeciesResponse, status_code=status.HTTP_201_CREATED)
def create_species(species: SpeciesCreate, db: Session = Depends(get_db)):
    # Check if scientific name exists
    existing = db.query(Species).filter(Species.scientificName == species.scientificName).first()
    if existing:
        raise HTTPException(status_code=400, detail="Especie con este nombre científico ya existe.")
    
    # Generate CUID-like ID (using uuid4 for simplicity)
    # Normally CUID is generated by @paralleldrive/cuid2 in Node, but UUID string is fine.
    # Prisma CUIDs are 25-30 chars, UUID is 36. Let's just use UUID string.
    new_id = "c" + str(uuid.uuid4()).replace("-", "")[:24]
    
    db_species = Species(
        id=new_id,
        name=species.name,
        scientificName=species.scientificName,
        categoryId=species.categoryId,
        description=species.description,
        habitat=species.habitat,
        imageUrl=species.imageUrl,
        status=species.status,
    )
    db.add(db_species)
    db.commit()
    db.refresh(db_species)
    
    # Eager load category for response
    return db.query(Species).options(joinedload(Species.category)).filter(Species.id == new_id).first()


@router.get("/categories", response_model=List[CategoryResponse])
def get_categories(db: Session = Depends(get_db)):
    return db.query(Category).order_by(Category.name.asc()).all()

@router.get("/species", response_model=List[SpeciesResponse])
def get_species(
    skip: int = 0, 
    limit: int = 100,
    categoria: Optional[str] = Query(None),
    habitat: Optional[str] = Query(None),
    estado: Optional[str] = Query(None),
    ordenar: Optional[str] = Query("nombre-asc"),
    db: Session = Depends(get_db)
):
    query = db.query(Species).options(joinedload(Species.category))
    
    if categoria:
        query = query.filter(Species.categoryId == categoria)
    if habitat:
        query = query.filter(Species.habitat.ilike(f"%{habitat}%"))
    if estado:
        query = query.filter(Species.status == estado)
        
    if ordenar == "nombre-desc":
        query = query.order_by(Species.name.desc())
    elif ordenar == "fecha-reciente":
        query = query.order_by(Species.createdAt.desc())
    elif ordenar == "fecha-antigua":
        query = query.order_by(Species.createdAt.asc())
    else:
        query = query.order_by(Species.name.asc())
        
    species = query.offset(skip).limit(limit).all()
    return species

@router.get("/species/habitats")
def get_habitats(db: Session = Depends(get_db)):
    habitats = db.query(Species.habitat).filter(Species.habitat.isnot(None)).distinct().all()
    return [{"habitat": h[0]} for h in habitats]

@router.get("/species/{species_id}", response_model=SpeciesDetailResponse)
def get_species_by_id(species_id: str, db: Session = Depends(get_db)):
    species = db.query(Species).options(
        joinedload(Species.category),
        joinedload(Species.photos),
        joinedload(Species.observations).joinedload(Observation.user)
    ).filter(Species.id == species_id).first()
    
    if species is None:
        raise HTTPException(status_code=404, detail="Species not found")
    return species

@router.get("/species/{species_id}/related", response_model=List[SpeciesResponse])
def get_related_species(species_id: str, db: Session = Depends(get_db)):
    species = db.query(Species).filter(Species.id == species_id).first()
    if species is None:
        raise HTTPException(status_code=404, detail="Species not found")
        
    related = db.query(Species).options(joinedload(Species.category)).filter(
        Species.categoryId == species.categoryId,
        Species.id != species_id
    ).limit(4).all()
    
    return related
